services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3000 
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vapi
      - SUMMARY_EMAIL=adi@choopil.com
    depends_on:
      - migrate 

  migrate:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./db:/db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: vapi
    depends_on:
      - db
    command: >
      sh -c "npx sequelize-cli --config /db/config.js --migrations-path /db/migrations db:migrate"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: vapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
